version: '3'
services:
  influxdb:
    image: influxdb:1.8.3
    container_name: influxdb
    volumes:
      # Mount for influxdb data directory
      - ./influxdb/data:/var/lib/influxdb
      # Mount for influxdb configuration
      - ./influxdb/config/:/etc/influxdb/
      - /etc/localtime:/etc/localtime:ro
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
    env_file:
      - ./influxdb/influxdb.env
  grafana:
    image: grafana/grafana:10.1.5
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/imgs/:/usr/share/grafana/public/img/custom
    depends_on:
      - influxdb
    env_file:
      - ./grafana/grafana.env
  telegraf:
    image: telegraf:1.18.2
    container_name: telegraf
    # Telegraf requires network access to InfluxDB
    ports:
      - "534:534/udp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # Mount for telegraf configuration
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      # Mount for Docker API access
      - /var/run/docker.sock:/var/run/docker.sock
  mqtt:
    image: eclipse-mosquitto:1.6.12
    container_name: mqtt-server
    hostname: mqtt-server
    ports:
      - '1884:1883'
volumes:
    grafana-storage:

